# Generated by Django 4.1.6 on 2023-02-03 23:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ShortURL",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("long_url", models.URLField(max_length=500)),
                ("shortened", models.CharField(blank=True, max_length=10, unique=True)),
                (
                    "expiration_date",
                    models.DateTimeField(
                        default=datetime.datetime(2023, 2, 10, 23, 46, 33, 25018)
                    ),
                ),
            ],
        ),
    ]
